name: release

on:
  push:
    branches:
      - "main"

jobs:
  app:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies (ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      # - name: linux signing key setup
      #   run: |
      #     echo -n "${{ secrets.GPG_SIGNING_KEY }}" | base64 --decode > gpg.key
      #     gpg --batch --passphrase "${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}" --import gpg.key
      #     echo "${{ secrets.GPG_SIGNING_KEY_ID }}:6:" | gpg --import-ownertrust
      #     rm gpg.key

      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.TEST_KEY }}
          passphrase: ${{ secrets.TEST_PASS }}
          fingerprint: ${{ secrets.TEST_KEY_ID }}
      - run: gpg --list-keys

      - uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          SIGN: 1
          SIGN_KEY: ${{ secrets.TEST_KEY_ID }}
          APPIMAGETOOL_SIGN_PASSPHRASE: ${{ secrets.TEST_PASS }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: appimage.AppImage
          path: src-tauri/target/release/bundle/appimage/sign-test_0.0.0_amd64.AppImage
